/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bouncingball;

import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author ANTHONYDALEJORDAN
 */
public class NameEntry extends javax.swing.JPanel {
    public static String name;
    JPanel panelWindows;
    CardLayout cardLayout;
    /**
     * Creates new form NameEntry
     */
    public NameEntry(JPanel panel) {
        initComponents();
        
        panelWindows = panel;
        cardLayout = (CardLayout) panelWindows.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHighScoreDisplay = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHighScoreDisplay.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        lblHighScoreDisplay.setForeground(new java.awt.Color(102, 102, 102));
        lblHighScoreDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHighScoreDisplay.setText("PLEASE ENTER YOUR NAME:");
        add(lblHighScoreDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 360, 50));

        txtName.setBackground(new java.awt.Color(204, 204, 204));
        txtName.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 380, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        name = txtName.getText();
        System.out.println("Yeah");
        
        cardLayout.show(panelWindows, "card2");
        JFrame.getFrames()[0].requestFocusInWindow();
        GamePanel.isRunning = true;
        
    }//GEN-LAST:event_txtNameActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

        txtName.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblHighScoreDisplay;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
